server {
  listen 80;
  server_name _;

  gzip on;
  gzip_types text/plain application/json application/javascript text/css application/xml text/javascript;

  location /api/catalog/ {
    proxy_pass http://catalog-service:8080/;
  }

  location /api/inventory/ {
    proxy_pass http://inventory-service:8080/;
  }

  location /api/promise/ {
    proxy_pass http://promise-service:8080/;
  }

  location /api/orders/ {
    proxy_pass http://order-service:8080/;
  }

  location /api/payments/ {
    proxy_pass http://payment-service:8080/;
  }

  location / {
    root   /usr/share/nginx/html;
    try_files $uri /index.html;
  }
}
